# Header
menu:
  Home: /
  Archives: /archives
  #There's an issue on the tag
  # Tags: /tags/tags

# SubNav
subnav:
  github: "#"
  rss: "#"
  facebook: "#"
  google: "#"
  twitter: "#"
  linkedin: "#"

rss: /atom.xml


# Content
excerpt_link: more
fancybox: true
mathjax: true

# Miscellaneous
google_analytics: ''
favicon: /favicon.png

#Services:

#Avatar url
avatar: ""
#Share Links
share: true
#Disqus
disqus_shortname: ''
#Tag Cloud
tagcloud: true

#Links
friends:
  Link 1: http://localhost:4000/
  Link 2: http://localhost:4000/
  Link 3: http://localhost:4000/
  Link 4: http://localhost:4000/
  Link 5: http://localhost:4000/
  Link 6: http://localhost:4000/

#About Me
aboutme: Hail Hydra..
